# Generated by Django 4.1.2 on 2022-12-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='Propietario',
        ),
        migrations.AddField(
            model_name='equipo',
            name='Mensaje',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
