# Generated by Django 4.1.2 on 2022-12-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_equipo_propietario_equipo_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='FestimadaDev',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='FlastMant',
            field=models.DateField(blank=True, null=True),
        ),
    ]
