# Generated by Django 4.1.2 on 2022-12-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_equipo_festimadadev_equipo_flastmant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='FestimadaDev',
            new_name='Fecha_estimada_devolución',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='FlastMant',
            new_name='Fecha_ultimo_mantenimiento',
        ),
    ]
