# Generated by Django 4.1.2 on 2022-12-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_festimadadev_equipo_fecha_estimada_devolución_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='Ubicacion',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
